### ISSUE TITLE
When applying classes for the items, it is rendering with spaces between each letter. Ex: "bg-danger" is rendering like "b g - d a n g e r"

### ISSUE THREAD

**Issue by vskgit** [richardtallent/vue-simple-calendar-sample#16]
When I apply any classes for the items, it taking extra spaces between each letter of that applied class. 

**Ex:** For the below item, the class name **_(classes: "bg-danger")_** is rendering like **"b g - d a n g e r"**. So the class is not working. Attached the screenshot of the rendered item with class name. Could you please respond ASAP.

{
	id: "e4",
	startDate: this.thisMonth(20),
	title: "My Birthday!",
	**_classes: "bg-danger",_**
	url: "https://en.wikipedia.org/wiki/Birthday",
}

![image](https://user-images.githubusercontent.com/23056054/123151150-cde26200-d480-11eb-8ee6-af08a11237dc.png)

Thanks in Advance.

**Comment by richardtallent** [comment]
Hi @vskgit,

As defined in the docs, the `classes` property should be an **array** of strings. E.g., `classes: ["bg-danger"]`. Passing a single string causes JavaScript to iterate the characters of the string.
