### ISSUE TITLE
Missing methods in App.vue

### ISSUE THREAD

**Issue by thisisforeagle** [richardtallent/vue-simple-calendar-sample#4]
`this.getFormattedWeekdayNames(this.userLocale, "long", 0)` on line 252
`this.today()` on lines 263 & 264

**Comment by richardtallent** [comment]
Hi,
It's not missing, it's included as part of CalendarMathMixin. Here's the source code for it:

https://github.com/richardtallent/vue-simple-calendar/blob/master/src/components/CalendarMathMixin.js#L251
